import React, { useState } from 'react';
import { Card } from '../components/common/Card';
import { Badge } from '../components/common/Badge';
import { Button } from '../components/common/Button';
import { SearchInput } from '../components/common/SearchInput';
import { AlertOctagon, Filter, CheckCircle2, Download, Clock } from 'lucide-react';

export const AlertsHistoryPage: React.FC = () => {
  const [searchTerm, setSearchTerm] = useState('');
  const [severityFilter, setSeverityFilter] = useState('ALL');

  const allAlerts = [
    {
      id: 'alt-101',
      timestamp: '2026-07-29 21:14:02',
      title: 'Volumetric SYN Flood Anomaly Detected',
      category: 'DDoS Attack',
      sourceIp: '185.220.101.44',
      targetIp: '10.0.4.12',
      severity: 'Critical',
      status: 'Investigating',
      ruleId: 'SIG-DDoS-901'
    },
    {
      id: 'alt-102',
      timestamp: '2026-07-29 21:02:18',
      title: 'Cobalt Strike Malleable C2 Beacon Heartbeat',
      category: 'Ransomware C2',
      sourceIp: '10.0.1.100',
      targetIp: '185.190.140.22',
      severity: 'Critical',
      status: 'Open',
      ruleId: 'SIG-C2-402'
    },
    {
      id: 'alt-103',
      timestamp: '2026-07-29 20:45:00',
      title: 'SQL Union Injection Payload on /api/v1/auth',
      category: 'SQL Injection',
      sourceIp: '192.168.1.105',
      targetIp: '10.0.1.5',
      severity: 'High',
      status: 'Mitigated',
      ruleId: 'SIG-WAF-112'
    },
    {
      id: 'alt-104',
      timestamp: '2026-07-29 19:30:15',
      title: 'High-Frequency Subnet Port Scan (Nmap Signature)',
      category: 'Port Reconnaissance',
      sourceIp: '103.45.12.88',
      targetIp: '10.0.0.0/24',
      severity: 'Medium',
      status: 'Resolved',
      ruleId: 'SIG-RECON-09'
    },
    {
      id: 'alt-105',
      timestamp: '2026-07-29 18:12:44',
      title: 'SSH Brute Force Authentication Threshold Exceeded',
      category: 'Credential Access',
      sourceIp: '45.142.120.9',
      targetIp: '10.0.2.14',
      severity: 'High',
      status: 'Mitigated',
      ruleId: 'SIG-AUTH-882'
    },
    {
      id: 'alt-106',
      timestamp: '2026-07-29 17:05:00',
      title: 'DNS Tunneling / Data Exfiltration Signature',
      category: 'Exfiltration',
      sourceIp: '10.0.1.88',
      targetIp: '8.8.8.8',
      severity: 'Critical',
      status: 'Resolved',
      ruleId: 'SIG-DNS-301'
    }
  ];

  const filteredAlerts = allAlerts.filter((alt) => {
    const matchesSearch =
      alt.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      alt.sourceIp.includes(searchTerm) ||
      alt.targetIp.includes(searchTerm) ||
      alt.ruleId.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesSeverity = severityFilter === 'ALL' || alt.severity.toUpperCase() === severityFilter.toUpperCase();
    return matchesSearch && matchesSeverity;
  });

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center space-x-3 mb-2">
            <div className="w-9 h-9 rounded-lg bg-red-500/20 border border-red-500/30 flex items-center justify-center text-red-400">
              <AlertOctagon className="w-5 h-5" />
            </div>
            <h2 className="text-xl font-bold text-white tracking-tight">Security Alerts & Incident History Log</h2>
          </div>
          <p className="text-sm text-slate-400">
            Real-time audit trail of all security alerts generated by AI detection models, signature heuristics, and SIEM rules.
          </p>
        </div>
        <div className="flex items-center space-x-3 shrink-0">
          <Button variant="secondary" size="sm">
            <Download className="w-4 h-4 mr-1.5" /> Export History (CSV)
          </Button>
          <Button variant="primary" size="sm">
            <CheckCircle2 className="w-4 h-4 mr-1.5" /> Mark All Selected Read
          </Button>
        </div>
      </div>

      {/* Filter Bar */}
      <Card>
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <SearchInput
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            placeholder="Filter alerts by IP, rule ID, or attack type..."
            className="w-full sm:w-80"
          />

          <div className="flex items-center space-x-2">
            <Filter className="w-4 h-4 text-slate-400" />
            <span className="text-xs font-mono text-slate-400">Severity:</span>
            {['ALL', 'CRITICAL', 'HIGH', 'MEDIUM'].map((level) => (
              <button
                key={level}
                onClick={() => setSeverityFilter(level)}
                className={`px-3 py-1 rounded text-xs font-mono transition-colors ${
                  severityFilter === level
                    ? 'bg-blue-600 text-white font-semibold'
                    : 'bg-slate-800 text-slate-300 hover:bg-slate-700'
                }`}
              >
                {level}
              </button>
            ))}
          </div>
        </div>
      </Card>

      {/* Alert Feed Table */}
      <Card title={`Alert Stream (${filteredAlerts.length} total events)`} subtitle="Sorted chronologically by alert trigger time">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono">
            <thead>
              <tr className="border-b border-slate-800 text-slate-400">
                <th className="pb-3 px-3">Timestamp</th>
                <th className="pb-3 px-3">Rule ID</th>
                <th className="pb-3 px-3">Alert Title</th>
                <th className="pb-3 px-3">Category</th>
                <th className="pb-3 px-3">Source IP</th>
                <th className="pb-3 px-3">Target IP</th>
                <th className="pb-3 px-3">Severity</th>
                <th className="pb-3 px-3 text-right">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/60">
              {filteredAlerts.map((alt) => (
                <tr key={alt.id} className="hover:bg-slate-800/40 transition-colors">
                  <td className="py-3 px-3 text-slate-400 flex items-center space-x-1.5">
                    <Clock className="w-3.5 h-3.5 text-slate-500" />
                    <span>{alt.timestamp}</span>
                  </td>
                  <td className="py-3 px-3 font-semibold text-slate-300">{alt.ruleId}</td>
                  <td className="py-3 px-3 font-sans font-medium text-slate-100">{alt.title}</td>
                  <td className="py-3 px-3 text-slate-300">{alt.category}</td>
                  <td className="py-3 px-3 text-blue-400 font-semibold">{alt.sourceIp}</td>
                  <td className="py-3 px-3 text-slate-300">{alt.targetIp}</td>
                  <td className="py-3 px-3">
                    <Badge variant={alt.severity as any}>{alt.severity}</Badge>
                  </td>
                  <td className="py-3 px-3 text-right">
                    <span
                      className={`px-2 py-0.5 rounded text-[11px] font-semibold ${
                        alt.status === 'Investigating'
                          ? 'bg-amber-500/10 text-amber-400 border border-amber-500/20'
                          : alt.status === 'Mitigated' || alt.status === 'Resolved'
                          ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20'
                          : 'bg-red-500/10 text-red-400 border border-red-500/20'
                      }`}
                    >
                      {alt.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
};
